import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/src/assets/styles/globals.scss";
import Providers from "@/src/providers/Providers";
import { SITE_NAME } from "@/src/constants/app.constants";
import { PropsWithChildren } from "react";
import { getSiteUrl } from "@/src/config/url.config";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  icons: {
    icon: '../favicon.ico'
  },
  title: {
    absolute: SITE_NAME,
    template: `%s | ${SITE_NAME}`
  },
  metadataBase: new URL(getSiteUrl()),
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    emails: ['info@test.com']
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: PropsWithChildren<unknown>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
        <div id="modal"></div>
      </body>
    </html>
  );
}
